
zero_confidence: 0% Traffic No Confidence
pre_release_analysis: Pre Release Analysis
low_confidence: Low Confidence: 5% Traffic
postReleaseAnalysis1: Post Release Analysis 1
postReleaseAnalysis2: Post Release Analysis 2
medium_confidence: Medium Confidence 30% Traffic
full_confidence: Full Confidence 100% Traffic


pre_release_analysis.style.fill: "#FF00FF"


zero_confidence -> pre_release_analysis: No Confidence
pre_release_analysis -> low_confidence: Run Query against APM
low_confidence -> postReleaseAnalysis1
postReleaseAnalysis1 -> medium_confidence
medium_confidence -> postReleaseAnalysis2
postReleaseAnalysis2 -> full_confidence


